/**
 * MyGamesCollection
 * This is a server for \"MyGamesCollection\" a site for curating and visualizing your collection of video games. [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: rmetcalf.codes@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package MyGamesCollection;

import io.swagger.model.Game;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * MyGamesCollection
 *
 * <p>This is a server for \"MyGamesCollection\" a site for curating and visualizing your collection of video games. [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API tests for GameApi 
 */
public class GameApiTest {


    private GameApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("https://virtserver.swaggerhub.com/RaesparkGames/GamesCollection/1.0.0", GameApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Add a new game to the db
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addGameTest() {
        Game body = null;
        //api.addGame(body);
        
        // TODO: test validations
        
        
    }
    
    /**
     * Deletes a game
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGameTest() {
        Long gameId = null;
        String apiKey = null;
        //api.deleteGame(gameId, apiKey);
        
        // TODO: test validations
        
        
    }
    
    /**
     * Gets all games owned by logged in user
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllGamesTest() {
        //api.getAllGames();
        
        // TODO: test validations
        
        
    }
    
    /**
     * Find game by ID
     *
     * Returns a single game
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGameByIdTest() {
        Long gameId = null;
        //Response response = api.getGameById(gameId);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Updates a pet in the store with form data
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePetWithFormTest() {
        Long gameId = null;
        String name = null;
        String status = null;
        //api.updatePetWithForm(gameId, name, status);
        
        // TODO: test validations
        
        
    }
    
}
